advcbv/advcbv/urls.py
from django.contrib import admin
from django.urls import path
from basic_app import views
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.IndexView.as_view()),
    url(r'^basic_app/',include('basic_app.urls',namespace='basic_app')),
]

advcbv/basic_app/templates/basic_app/learning_templates/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

#untuk TEMPLATEA TAGGING
app_name = 'basic_app'

urlpatterns = [
    url(r'^relative/$',views.relative,name='relative'),
    url(r'^other/$',views.other,name='other')

]

advcbv/basic_app/templates/basic_app/learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path
from basic_app import views
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('basic_app/',include('basic_app.urls')),
]

advcbv/basic_app/urls.py
from django.conf.urls import url,include
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    url(r'^$',views.SchoolListView.as_view(),name='list'),
    url(r'^(?P<pk>\d+)/$',views.SchoolDetailView.as_view(),name='detail'),
    url(r'^create/$',views.SchoolCreateView.as_view(),name='create'),
    url(r'^update/(?P<pk>\d+)/$',views.SchoolUpdateView.as_view(),name='update'),
    url(r'^delete/(?P<pk>\d+)/$',views.SchoolDeleteView.as_view(),name='delete'),

]

advcbv/basic_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("basic_app:detail",kwargs={'pk':self.pk})


class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School,related_name='students',on_delete=models.CASCADE)

    def __str__(self):
        return self.name

advcbv/basic_app/templates/basic_app/learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

advcbv/basic_app/templates/basic_app/learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'hello world','number':100}
    return render(request,'basic_app/index.html',context_dict)

def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relative_url_template.html')    

advcbv/basic_app/views.py
from django.shortcuts import render
from django.urls import reverse,reverse_lazy
from django.views.generic import (View,TemplateView,
                                ListView,DetailView,
                                CreateView,UpdateView,
                                DeleteView)
from django.http import HttpResponse
from . import models

# Create your views here.

class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School
    #it will auto generete return school_list. mantep
    #atau apake variable yg context_object_name buat overide list yg otomatis

class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'basic_app/school_detail.html'

class SchoolCreateView(CreateView):
    fields = ('name','principal','location')
    model = models.School

class SchoolUpdateView(UpdateView):
    fields = ('name','principal')
    model = models.School

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("basic_app:list")
'''
class CBView2(View):
    def get(self,request):
        return HttpResponse("CLASS BASED VIEWS ARE COOL!")
'''
class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['injectme'] = 'BASIC INJECTION'
        return context

advcbv/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
  </head>
  <body>

    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
      <ul class="nav navbar-nav">
        <li><a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a></li>
        <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
      </ul>
      </div>
    </nav>

    <div class="container">
        {% block body_block %}

        {% endblock %}

    </div>

  </body>
</html>

advcbv/basic_app/templates/basic_app/learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar brand" href="{% url 'index' %}" >BRAND</a></li>
          <li><a class="navbar brand" href="{% url 'admin:index' %}" >Admin</a></li>
          <li><a class="navbar brand" href="{% url 'basic_app:other' %}">Other</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      <!-- anything outside of this will be inherited if you extend! -->

      {% endblock %}


    </div>
  </body>
</html>

advcbv/basic_app/templates/basic_app/learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% load my_extras %}
  {% block body_block %}
   <h1>WELCOME TO INDEX!</h1>
   <h2>This is index.html page showing!</h2>
   =====================custom filter==================
   <h1>{{ text|ilang:'world' }}</h1>
   <h2>{{ number|add:99 }}</h2>
  {% endblock %}

advcbv/basic_app/templates/basic_app/learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}
   <h1>WELCOME TO OTHER!</h1>
   <h2>This is an example of template inheritance!</h2>
  {% endblock %}

advcbv/basic_app/templates/basic_app/learning_templates/templates/basic_app/relative_url_template.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>WELCOME TO RELATIVE URL TEMPLATES</h1>
    <a href="{% url 'basic_app:other' %}">THE OTHER PAGE</a>
    <a href="{% url 'admin:index' %}">LINK TO ADMIN</a>
    <a href="{% url 'index' %}">LINK TO INDEX</a>
  </body>
</html>

advcbv/basic_app/templates/basic_app/school_confirm_delete.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}
<h1>Delete {{ school.name}}?</h1>
<form method="post">
  {% csrf_token %}
  <input type="submit" class='btn btn-danger'  value="delete">
  <a href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>
</form>

{% endblock %}

advcbv/basic_app/templates/basic_app/school_detail.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}
<div class="jumbotron">
  <h1>Welcome to DETAILS and member of the school!</h1>
    <h2>School details:</h2>
    <p>Name: {{ school_detail.name }}</p>
    <p>Principal: {{ school_detail.principal }}</p>
    <p>Location: {{ school_detail.location }}</p>
    <h3>Student:</h3>
    {% for student in school_detail.students.all %}
      <p>{{student.name}} who is {{student.age}} years old</p>

    {% endfor %}
</div>

<div class="container">
  <p><a class='btn btn-warning' href="{% url 'basic_app:update' pk=school_detail.pk %}">Update</a>
  <a class='btn btn-primary' href="{% url 'basic_app:delete' pk=school_detail.pk %}">Delete</a></p>
</div>

{% endblock %}

advcbv/basic_app/templates/basic_app/school_form.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}

<h1>
  {% if not form.instance.pk %}
  Create School
  {% else %}
  Update School
  {% endif %}

</h1>

<form method="post">
   {% csrf_token %}
   {{ form.as_p }}
   <input type="submit" class="btn btn-primary" value="submit">

</form>

{% endblock %}

advcbv/basic_app/templates/basic_app/school_list.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}
<div class="jumbotron">
<h1>Welcome to a list SEKOLAH!</h1>
  <ol>
    {% for school in schools %}
    <h2><li><a href="{{school.id}}">{{school.name}}</a></li></h2>
    {% endfor %}
  </ol>
</div>
{% endblock %}

advcbv/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
  </head>
  <body>

    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
      <ul class="nav navbar-nav">
        <li><a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a></li>
        <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
      </ul>
      </div>
    </nav>

    <div class="container">
        {% block body_block %}

        {% endblock %}

    </div>

  </body>
</html>

advcbv/templates/index.html
{% extends "base.html" %}
{% block body_block %}

<div class="jumbotron">
  <h1>Home Page!</h1>
</div>

{% endblock %}